# Relative Positionen in % von der oberen linken Ecke
import os
from dotenv import load_dotenv


X_FIELD = 6
Y_FIELD = 7.2
WIDTH_FIELD = 88
HEIGHT_FIELD = 70

X_CARDS = 22.1
Y_CARDS = 83
WIDTH_CARD = 18.9
HEIGHT_CARD = 13

X_ELIXIR = 27
Y_ELIXIR = 96.65
WIDTH_ELIXIR = 70.5
HEIGHT_ELIXIR = 2.55

X_NEXT_CARD = 5.5
Y_NEXT_CARD = 93.5
WIDTH_NEXT_CARD = 8.5
HEIGHT_NEXT_CARD = 5.75


#Vektor längen
FIELD_MTRX_W = 9
FIELD_MTRX_H = 16
ELIXIR_VECTOR = 1
CARDS_VECTOR = 4
NEXT_CARD_VECTOR = 1
ALLY_TOWER_VECTOR = 3
ENEMY_TOWER_VECTOR = 3
VECTOR_LENGTH = ELIXIR_VECTOR + CARDS_VECTOR + NEXT_CARD_VECTOR + ALLY_TOWER_VECTOR + ENEMY_TOWER_VECTOR + FIELD_MTRX_H * FIELD_MTRX_W

#Keys für Eigenschaften
KEY_ELIXIR = "elixir"
KEY_CARDS = "cards"
KEY_NEXT_CARD = "next_card"
KEY_FIELD = "field"


#.env Variablen
load_dotenv()
ROBOFLOW_API_KEY = os.getenv("ROBOFLOW_API_KEY")
WORKSPACE_NAME = os.getenv("WORKSPACE")
WORKFLOW_FIELD_DETECTION = os.getenv("WORKFLOW_FIELD_DETECTION")
WORKFLOW_CARD_DETECTION = os.getenv("WORKFLOW_CARD_DETECTION")