import os
from dotenv import load_dotenv

# Relative Positionen in % von der oberen linken Ecke
X_ELIXIR = 26.5
Y_ELIXIR = 98
WIDTH_ELIXIR = 69.6
# HEIGHT_ELIXIR = 2.2

X_CARDS = 21.9
Y_CARDS = 81.5
WIDTH_CARD = 18.7
HEIGHT_CARD = 14

X_NEXT_CARD = 5.2
Y_NEXT_CARD = 93.2
WIDTH_NEXT_CARD = 8.5
HEIGHT_NEXT_CARD = 5.75

X_FIELD = 6
Y_FIELD = 7.2
WIDTH_FIELD = 88
HEIGHT_FIELD = 69.5

X_KING = 44.5
Y_ALLY_KING = 75.5
Y_ENEMY_KING = 3
WIDTH_KING= 15
# HEIGHT_KING = 1

X_LEFT_PRINCESS = 20.05
X_RIGHT_PRINCESS = 72.45
Y_ALLY_PRINCESS = 62.15
Y_ENEMY_PRINCESS = 15.2
WIDTH_PRINCESS = 10.95
# HEIGHT_PRINCESS = 0.8

#Keys für Eigenschaften
KEY_ELIXIR = "elixir"
KEY_CARDS = "cards"
KEY_NEXT_CARD = "next_card"
KEY_ALLY_KING = "ally_king"
KEY_ALLY_PRINCESSES = "ally_princesses"
KEY_ENEMY_KING = "enemy_king"
KEY_ENEMY_PRINCESSES = "enemy_princesses"
KEY_FIELD = "field"


#.env Variablen
load_dotenv()
ROBOFLOW_API_KEY = os.getenv("ROBOFLOW_API_KEY")
WORKSPACE_NAME = os.getenv("WORKSPACE")
WORKFLOW_FIELD_DETECTION = os.getenv("WORKFLOW_FIELD_DETECTION")
WORKFLOW_CARD_DETECTION = os.getenv("WORKFLOW_CARD_DETECTION")

#Vektor längen
STATE_FIELD_MTRX_H = 8
STATE_FIELD_MTRX_W = 5
ELIXIR_VECTOR = 1
CARDS_VECTOR = 4
NEXT_CARD_VECTOR = 1
ALLY_TOWER_VECTOR = 3
ENEMY_TOWER_VECTOR = 3
STATE_VECTOR_LENGTH = ELIXIR_VECTOR + CARDS_VECTOR + NEXT_CARD_VECTOR + ALLY_TOWER_VECTOR + ENEMY_TOWER_VECTOR + STATE_FIELD_MTRX_H * STATE_FIELD_MTRX_W

#State Vektor start, ende
ELIXIR_START = 0
CARDS_START = ELIXIR_START + ELIXIR_VECTOR
NEXT_CARD_START = CARDS_START + CARDS_VECTOR
ALLY_TOWER_START = NEXT_CARD_START + NEXT_CARD_VECTOR
ENEMY_TOWER_START = ALLY_TOWER_START + ALLY_TOWER_VECTOR
FIELD_START = ENEMY_TOWER_START + ENEMY_TOWER_VECTOR
FIELD_END = FIELD_START + STATE_FIELD_MTRX_H * STATE_FIELD_MTRX_W
 


#Action anzahl (Matrix )
ACTION_FIELD_MTRX_H = 5
ACTION_FIELD_MTRX_W = 3
ACTION_SIZE = (4 * ACTION_FIELD_MTRX_H * ACTION_FIELD_MTRX_W) + 1